### ISSUE TITLE
Add to conda

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#122]
https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by kjappelbaum** [comment]
would be awesome to have it on `conda-forge`, I was about to add a recipe for one of my packages (https://github.com/kjappelbaum/element-coder/issues/13) --- however, I depend on `sciris` also being distributed via conda. 

Since the dependencies of `sciris` are not too crazy, it shouldn't be too hard to add a recipe.  I can help with that if needed.

**Comment by kjappelbaum** [comment]
created a basic recipe https://github.com/conda-forge/staged-recipes/pull/19636

I added you as maintainer

**Comment by kjappelbaum** [comment]
one question I had (but didn't have the time to test): is Python 3.9 really the lower bound? (Or do you also support Py3.7/3.8?)

**Comment by kjappelbaum** [comment]
limiting the recipe seems to be the [ansicolors](https://github.com/jonathaneunice/colors) package, which doesn't to be that well maintained. An alternative might be [rich](https://rich.readthedocs.io/en/stable/index.html) -- or I can also make a recipe for ansicolors.

**Comment by kjappelbaum** [comment]
@cliffckerr if you can give me feedback about the ansicolors package, I can already proceed with this :)

**Comment by cliffckerr** [comment]
@kjappelbaum Thank you and sorry for the delay! Yes happy to move away from `ansicolors`. Do you have a sense for if there's a "common" solution for Conda-based projects? I noticed `celery` uses a [bespoke solution](https://github.com/celery/celery/blob/master/celery/utils/term.py) and [optuna](https://github.com/optuna/optuna/blob/master/setup.py) uses `colorlog`, neither of which are quite what we want here...

**Comment by kjappelbaum** [comment]
Thanks, I guess you currently only use it here https://github.com/sciris/sciris/blob/fc0148fd9352e443a1c9b1a790275bc2904b30b1/sciris/sc_printing.py#L638-L661? 

Options I see:
- I think all this formatted and colored printing can be handled using [rich](https://rich.readthedocs.io/en/stable/index.html). 
- You already depend on [colorama](https://pypi.org/project/colorama/) (which is also on conda). You should also be able to use it for what you use `ansicolors` at the moment 
- You can replicate the functionality yourself using something like
```
class Colors(enum):
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
```
- You can use [termcolor](https://pypi.org/project/termcolor/)

**Comment by cliffckerr** [comment]
Removing from the 2.0.0 milestone since technically this should only be done after the milestone is complete :)

**Comment by cliffckerr** [comment]
@kjappelbaum Sciris 2.0 has been released! The `ansicolors` dependency was removed and additional information has been added to `setup.py` (additional Python versions, for example). Do you want to try running the tests on the `conda` recipe again?

**Comment by kjappelbaum** [comment]
Nice!

BTW, there is now also an `ansicolors` conda recipe https://github.com/conda-forge/staged-recipes/pull/19885.

**Comment by cliffckerr** [comment]
Oh awesome! Thanks @kjappelbaum  :)

**Comment by cliffckerr** [comment]
Hi @kjappelbaum , the Sciris paper is now under review at [JOSS](https://github.com/openjournals/joss-reviews/issues/5029) -- do you want to update the [recipe](https://github.com/conda-forge/staged-recipes/pull/19636), or want me to?

**Comment by kjappelbaum** [comment]
Hi @cliffckerr. Happy New Year! I can check what the build fails in the next few days (I think it was a missing dependency). In case I'm too slow, feel free to give it a shot in the meantime.

**Comment by cliffckerr** [comment]
Created a new PR here: https://github.com/conda-forge/staged-recipes/pull/22662
Comment on old PR here: https://github.com/conda-forge/staged-recipes/pull/19636#issuecomment-1518916570

**Comment by cliffckerr** [comment]
Done! https://github.com/conda-forge/staged-recipes/pull/22662
