### ISSUE TITLE
Issue reading date formats

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#137]
```
sc.readdate("Tue 2020-09-29 15:48:05", dateformat='%a %Y-%m-%d %T')
```

**Comment by appsplash99** [comment]
Hey Hello there,
I am new to opensource but not to python, however, i might be wrong but here's why the above issue might have occured:

The source code related to the readdate is located in this file: sciris/sciris/sc_utils.py.
In line 1237 readdate function is defined, its implementation is such that it uses datetime module and looks for a format in the below dictinary called formats_to_try :

`formats_to_try = {
        'date':           '%Y-%m-%d', # 2020-03-21
        'date-alpha':     '%Y-%b-%d', # 2020-Mar-21
        'date-numeric':   '%Y%m%d',   # 20200321
        'datetime':       '%Y-%m-%d %H:%M:%S',    # 2020-03-21 14:35:21
        'datetime-alpha': '%Y-%b-%d %H:%M:%S',    # 2020-Mar-21 14:35:21
        'default':        '%Y-%m-%d %H:%M:%S.%f', # 2020-03-21 14:35:21.23483
        'ctime':          '%a %b %d %H:%M:%S %Y', # Sat Mar 21 23:09:29 2020
        }`

In our issue case, we are supplying the '%T' for '15:48:05' but the code is unable to find it.

Fixing Issue: What we can do is instead use:
sc.readdate("Tue 2020-09-29 15:48:05", dateformat='%a %Y-%m-%d %H:%M:%S'),
which is available in the formats_to_try dictionary.

I hope this helps and if not please do let me know 😄

**Comment by cliffckerr** [comment]
Hi @appsplash99 , thank you so much for your comment! This indeed does fix it. `%T` is a valid time code in some cases (here, `git log`) but not for Python. But the real issue is that the way `readdate()` is written, it doesn't pass on exceptions. In this case the exception `strptime()` raises is quite clear, `ValueError: 'T' is a bad directive in format '%a %Y-%m-%d %T'`. This issue will be fixed in the next release of Sciris, hopefully in a few weeks.

**Comment by appsplash99** [comment]
Can i do it?

**Comment by cliffckerr** [comment]
Sure, go ahead! Thank you!

**Comment by appsplash99** [comment]
Wait! I don't think there's any error here:
I think our application of using`%T` is inapplicable.

The reason why:
Even if i use `%T` with datetime as it is , we still get an error:
```
INPUT:
datetime_str = '09/19/18 10:55:26'
datetime_object = datetime.strptime(datetime_str, '%m/%d/%y %T')
print(datetime_object) 

OUTPUT:
ValueError: 'T' is a bad directive in format '%m/%d/%y %T'
```

So, you can use`%X` instead which is `Locale’s appropriate time representation. - 21:30:00 (en_US); 21:30:00 (de_DE)`

<ins>Another Fix:</ins>
## sc.readdate("Tue 2020-09-29 15:48:05", dateformat='%a %Y-%m-%d %X')

Hope this Helps 😄 👍
