### ISSUE TITLE
Parallelize limit ncpus

### ISSUE THREAD

**Issue by RomeshA** [sciris/sciris#197]
It would be nice if `sc.parallelize` had the `ncpus` default to the smaller of the number of CPUs and the number of tasks, rather than just the number of CPUs

**Comment by cliffckerr** [comment]
Agree! Also, I so often finding myself having to import multiprocessing separately just to get cpu_count(), so want to make an alias for that in Sciris too.

**Comment by cliffckerr** [comment]
Done
