### ISSUE TITLE
Fix sc.sanitize() for multidimensional arrays

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#282]
```py
n = int(100e3)
a = pl.rand(n)
b = pl.rand(1, n)

with sc.timer('a'): sc.sanitize(a)
with sc.timer('b'): sc.sanitize(b)
```

**Comment by cliffckerr** [comment]
Do not assume 0 by default

**Comment by pausz** [comment]
brainlog

```python
data = [[],[2,4,np.nan]]  # fails
data = [[None],[2,4,np.nan]]  # fails
data = [[1,2,3],[2,4,np.nan]] # doesn't fail but returns nonsensical output
```

```
import sciris as sc
import numpy as np
n = int(1e3)
c = np.random.rand(1, n)
c = np.where(c < 0.5, np.nan, c) # shape (1, n)
sc.sanitize(c) # doesn't fail but output array shape is (number of non-nans, n)
```

**Comment by pausz** [comment]
+ What should sc.sanitize() assume the sanitised array is empty? Return empty array directly?
+ What datatypes should sc.sanitize() handle? arrays and lists? other?
+ Consider writing a separate function for multidimensional arrays (ie, _sanitizend) that is called by sanitize if data is multidimensional? 

+ For input arrays of shape(1, n), if replacenans=True, do we want the output array to have shape (1, n). And if replacenans-False, do we want to preserve the singleton axis too?
