### ISSUE TITLE
`dcp` die by default?

### ISSUE THREAD

**Issue by RomeshA** [sciris/sciris#288]
Occasionally deep-copying fails with errors like 

```
Warning: could not perform deep copy, performing shallow instead: cannot pickle '_thread.RLock' object
```

However, the default behaviour of `sc.dcp` is to revert to doing a shallow copy instead. However, in general users would use `sc.dcp` if they actually need a deep copy of the object - in particular, if they are making changes to the copy that should not be propagated back to the original object. If something happens to an object that causes `dcp` to fail, with `die=False` by default, the code will print a warning but will just continue on with a shallow copy. I think this probably carries a high risk of the subsequent calculations yielding incorrect results, in potentially difficult to detect ways e.g. if an in-place math operation like `*=` is being used on the copy? The case that particularly concerns me is if something changes in a dependency that stops `dcp` from working (so it wasn't happening at the original time of development) and if it gets raised in an RPC for a web tool (in which case the user won't see any warnings). @cliffckerr what do you think about changing the default to `die=True` so that if the developer encounters such an error, it needs to be overridden on a case-by-case basis if the developer is sure that using a shallow copy will still yield correct results. I think that would also better reflect the potential severity of `dcp` failing and the copy not actually being a deep copy. Arguably, that's also a sign that `sc.dcp()` wasn't needed in the first place.

**Comment by cliffckerr** [comment]
Done
