### ISSUE TITLE
Error when loading pickled pre-1.3 sciris Spreadsheet

### ISSUE THREAD

**Issue by RomeshA** [sciris/sciris#290]
A pre-1.3 sciris spreadsheet has no attribute `self.wb`. After loading the spreadsheet, `.openpyxl()` fails because it has

```
    def openpyxl(self, reload=False, store=True, **kwargs):
        ''' Return a book as opened by openpyxl '''
        wb = self.wb
        if self._reload_wb(reload=reload):
            import openpyxl # Optional import
            if self.blob is not None:
 ```

because `self.wb` does't exist. `self._reload_wb` does check for `(not hasattr(self, 'wb'))` but only _after_ `self.wb ` has been accessed. Probably the `wb=self.wb` should go into an 'else' statement

```
if self._reload_wb(reload=reload):
    ...
else:
    wb = self.wb
 ```

**Comment by cliffckerr** [comment]
Done
