### ISSUE TITLE
Check if sc.options(fontsize=16) works

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#304]

**Comment by pausz** [comment]
Works for me. Tried the following on Ipython

```python
import pylab as pl
import sciris as sc

sc.options(fontsize=16)
data = pl.rand(5,4)
sc.bar3d(data)
pl.show()

sc.options(fontsize=32)
data = pl.rand(5,4)
sc.bar3d(data)
pl.show()

```
![scoptions_fontsize_16](https://user-images.githubusercontent.com/1563810/165417881-fdd524c3-e4fe-4c6f-8fc7-c01131dad058.png)
![scoptions_fontsize_32](https://user-images.githubusercontent.com/1563810/165417890-6fb28bf7-a8b1-4ed5-9c70-9637077cb604.png)

**Comment by cliffckerr** [comment]
Agree, seems to be working!
