### ISSUE TITLE
Check if environment variables work

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#313]
This doesn't seem to work -- would need to set backend on import:
```
export SCIRIS_BACKEND='agg' # Don't show plots
```

**Comment by pausz** [comment]
![Screenshot from 2022-06-07 14-25-56](https://user-images.githubusercontent.com/1563810/172295791-397cba56-4b66-45b3-871f-22b14ebecb2e.png)

**Comment by pausz** [comment]
Shouldn't default values be sciris' defaults rather than the ones given in the env variables?

**Comment by cliffckerr** [comment]
Going to pull from Covasim: #343
