### ISSUE TITLE
Remove ansicolors dependency

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#332]
Not supported by `conda` build scripts -- can just include `ansicolors` [code](https://github.com/jonathaneunice/colors/blob/master/colors/colors.py) directly perhaps, or use `colorama` and deprecate the `colors` syntax.

**Comment by kjappelbaum** [comment]
Do you have any preferred way of implementing this? I might be able to help out with a PR?

**Comment by cliffckerr** [comment]
Thanks @kjappelbaum ! I'm actually thinking that maybe the best-for-the-community approach would be to build a conda recipe for `ansicolors` as you mentioned before -- it seems to be a [pretty widely used package](https://pepy.tech/project/ansicolors) (>10M downloads), so maybe others would benefit from this as well? Another approach would be to incorporate the ~100 lines of `ansicolors`' code into `sciris`, which seems to be allowed by the ISC license (with attribution). That strikes me as being a potentially easier but also potentially less collegial approach. What do you think?

**Comment by kjappelbaum** [comment]
Personally, I like keeping dependencies minimal. Hence, I'd just reuse `colorama` or a custom `enum`. 

However, I get the point that `aniscolors` is widely used. I'll open an issue over there if the maintainer (if still active ...) is OK with me creating a recipe for it.

**Comment by kjappelbaum** [comment]
Made a recipe, https://github.com/conda-forge/staged-recipes/pull/19885. Let's see if we can get it merged soon.

**Comment by cliffckerr** [comment]
Closed by #348 , see commit [here](https://github.com/sciris/sciris/pull/348/commits/88f86848e08f80842fc31fcd73f4a5c7b4046ac9)
