### ISSUE TITLE
Align saveobj(die=True) with loadobj(die=True)

### ISSUE THREAD

**Issue by RomeshA** [sciris/sciris#386]
`loadobj(die=True)` means that it an unpickling error will stop trying to load the file and just raise the error. Specifically, this is useful if you know that the file was saved and should load with `pickle` and never want it to fall back to `dill` etc. 

However, `saveobj(die=True)` has different behaviour, relating only to if the user tries to save an empty file. It would be great to have `saveobj(die=True)` match `loadobj(die=True)` so that it too raises an error if the first attempt at saving fails

**Comment by cliffckerr** [comment]
Closed by https://github.com/sciris/sciris/pull/387
