### ISSUE TITLE
Support zstandard for compression

### ISSUE THREAD

**Issue by fabmazz** [sciris/sciris#389]
It would be great if when saving an object with `sc.saveobj` instead of using gzip compression, it would be possible to use zstandard, which is much faster in compression and decompression while keeping the same compression ratio.

**Comment by cliffckerr** [comment]
Thanks @fabmazz , will look into this for the 2.0.5 release!

**Comment by pausz** [comment]
Some resources: 
- https://github.com/indygreg/python-zstandard
- https://python-zstandard.readthedocs.io/en/latest/compressor.html
- https://pypi.org/project/zstd/

**Comment by pausz** [comment]
@cliffckerr 
- `zstandard` is consistently faster than gzip for tests with moderately complex and complex objects. Roughly speaking zstd is 50% faster for a compression level = 5. 
- On the other hand, for cases where a numpy array or pandas dataframe are the objects being saved, benchmarks show that gzip is faster. Though in those cases both gzip and zstd operate at submillisecond scales.
---
I've temporarily added `zstd` as an alternative compressor in [`sc.save()` on a new branch](https://github.com/sciris/sciris/blob/rc2.0.5-389-zstandard/sciris/sc_fileio.py#L230). It's incomplete as it was only for the purpose of benchmarking execution times.

About this benchmark: 
- Purpose: to assess execution time of sc.save() for: 
- gzip and zstd, 
- x3 compression levels (1, 5 - default, 9)
- 4x objects of different levels of complexity:
    - numpy array
    - pandas dataframe
    - covasim sim object 
       - 2x simulation lengths
    - covasim multisim object
       - 2x values of repetitions

- each combination of the above parameters was executed 50 times.  
- the benchmark was repeated on two different drives.  

Files:
- [benchmarking script ](https://github.com/sciris/sciris/blob/rc2.0.5-389-zstandard/tests/benchmarks/benchmark_saveobj_compressors.py) 
-  [csv files](https://github.com/sciris/sciris/tree/rc2.0.5-389-zstandard/tests/benchmarks/files) with the mean execution time of sc.saveobj 
 

Note: In the csv files the values in the percentage change column are estimated as ((gzip_time - zstd_time) / gzip_time)*100, given a specific object and a compression level. Negative % values indicate zstd is slower than gzip.   

Example: results for a complex object (covasim multisim); durations expressed in seconds:

| Compressor| 1 | 5 | 9 |
|----------|----|----|----|
gzip | 0.0785467672348022 | 0.11664342880249 | 0.957848591804504
zstd | 0.0497555065155029 | 0.0676418399810791 | 0.0893397521972656
percentage change | 36.65 | 42.00 | 90.67

**Comment by cliffckerr** [comment]
Closed by #404

**Comment by cliffckerr** [comment]
Thanks @fabmazz , zstandard is now incorporated into Sciris 2.1.0! You can use it with `sc.save(compression='zstd')`, or by using `sc.zsave()`.  `sc.load()` will now work with both gzip and zstandard files.
