### ISSUE TITLE
Unclear who precisely is the target audience

### ISSUE THREAD

**Issue by aflaxman** [sciris/sciris#411]
https://github.com/sciris/sciris/blob/cf6ca0c6805c32595fed3140411391a780380bd4/paper.md?plain=1#L92

I would like a clear statement of who the target audience of this package is by this point.  See openjournals/joss-reviews#5076 for more detail.

**Comment by tacaswell** [comment]
I very much agree with this concern.  "Simple" is very much in the eye of the beholder: the more the API encodes your personal assumptions the simpler it seems.  However baking more assumptions into an API is not a cost-free activity as now someone who has different assumptions will find the tool much harder to use.

In addition to a discussion of who the intended audience is (and the assumptions they want to make), I would also like to see a discussion of the path for users who grow needs beyond the reduced interface that sciris provides.

**Comment by cliffckerr** [comment]
Added to the first paragraph of the "Statement of need":
> For some scientists, this increasing reliance on software has created a barrier between themselves and the science they want to do. It is these people – people who want things to "just work" rather than worry about the implementation details – who are the primary audience for Sciris. (In contrast, people who always use type hints in their code will likely *not* find Sciris to be as helpful.)

Working on part 2...

**Comment by cliffckerr** [comment]
Added a "Beyond Sciris" section

**Comment by aflaxman** [comment]
👍
