### ISSUE TITLE
list comprehension here is cheating a little

### ISSUE THREAD

**Issue by aflaxman** [sciris/sciris#412]
Using a list comprehension here is cheating a little, if your goal is to make this understandable to novice python users (are they your target audience?)

https://github.com/sciris/sciris/blob/cf6ca0c6805c32595fed3140411391a780380bd4/misc/showcase_sciris.py#L20

**Comment by tacaswell** [comment]
As the other JOSS reviewer I'm going to disagree, I think that list comprehensions are a reasonable thing to expect novice programmers to use.  list comprehensions (and dict comprehensions) are a super powerful tool in core-Python that scientists would be very well served to learn.

**Comment by cliffckerr** [comment]
I agree with that list comprehensions can definitely get out of hand and confuse novice (or even experienced) Python users. I hope this is not an example of that! I'll clarify the audience as part of a separate issue, but, in short, while novice users are part of the audience, they are not the only (or even main) audience.

Will leave as-is.

**Comment by cliffckerr** [comment]
cc https://github.com/openjournals/joss-reviews/issues/5076

**Comment by aflaxman** [comment]
👌
