### ISSUE TITLE
Reduction is not 5-fold

### ISSUE THREAD

**Issue by aflaxman** [sciris/sciris#413]
https://github.com/sciris/sciris/blob/cf6ca0c6805c32595fed3140411391a780380bd4/paper.md?plain=1#L103

Going from 55 lines to 29 lines is not a five-fold reduction... it's not even twofold.

/cc https://github.com/openjournals/joss-reviews/issues/5076

**Comment by cliffckerr** [comment]
Clarified in the caption: "Comparison of functionally identical scripts without Sciris (left) and with Sciris (right), showing a nearly five-fold reduction in lines of code required **(excluding whitespace, comments, and the shared "wave generator" code), from 33 to 7**".

This could instead be illustrated by removing comments and whitespace and putting the `randwave` function in a separate script, but I feel the version here is clearer.

**Comment by aflaxman** [comment]
👍
