### ISSUE TITLE
sciris on conda-forge?

### ISSUE THREAD

**Issue by krosenfeld** [sciris/sciris#422]
It would be great (for me) to install sciris using conda. It seems like it would be straightforward to add to conda-forge? Is there a reason the project prefers to be installed by pip?

**Comment by cliffckerr** [comment]
Thanks @krosenfeld -- I've been working with @kjappelbaum to get that working (https://github.com/sciris/sciris/issues/122). I'll take a look and hopefully we can (finally!) do this in the next week or so.

**Comment by krosenfeld** [comment]
That's super! Thank you.

**Comment by cliffckerr** [comment]
Hi @krosenfeld , sorry for the delay, but I made a new conda-forge PR, hopefully it will be available soon!
 https://github.com/conda-forge/staged-recipes/pull/22662

**Comment by krosenfeld-IDM** [comment]
Thanks Cliff!

**Comment by cliffckerr** [comment]
Done, should be live in the next few days! https://github.com/conda-forge/staged-recipes/pull/22662
