### ISSUE TITLE
docs sc_parallal.parallelize are inconsistent

### ISSUE THREAD

**Issue by tacaswell** [sciris/sciris#427]
https://sciris.readthedocs.io/en/latest/_autosummary/sciris.sc_parallel.parallelize.html#sciris-sc-parallel-parallelize

> Note: the default parallelizer "multiprocess" uses dill for pickling, so is the most versatile (e.g., it can pickle non-top-level functions). However, it is also the slowest for passing large amounts of data. You can switch between these with parallelizer='fast' (concurrent.futures) and parallelizer='robust' (multiprocess).

I assume the last parenthetical should be `multiprocessing` as that is what is mentioned in the docstring on the parameter?  Would it be possible to provide the expected signature if a user supplies a function?

**Comment by cliffckerr** [comment]
Good catch -- there was indeed one mention of `multiprocessing` that should have been `multiprocess` -- does this PR address the issue?
https://github.com/sciris/sciris/pull/445

cc https://github.com/openjournals/joss-reviews/issues/5076

**Comment by tacaswell** [comment]
I still find https://sciris.readthedocs.io/en/latest/api/_autosummary/sciris.sc_parallel.parallelize.html#parallelize quite confusing.  I think I am thrown by the things in the () being not string but also be aliases for the string is `parallizer='...'` they follow.

For consistency do you also want to support `'threadpool-copy'` as a valid input?
