### ISSUE TITLE
Clarify installation

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#429]
cc https://github.com/openjournals/joss-reviews/issues/5076

**Comment by cliffckerr** [comment]
Duplicate of https://github.com/sciris/sciris/issues/429

**Comment by danielskatz** [comment]
I think you meant duplicate of #439 🙂

**Comment by cliffckerr** [comment]
@danielskatz Ha, I did, although I suppose it's a deep philosophical question whether or not it's also a duplicate of itself ;)
