### ISSUE TITLE
Overall R1 comments

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#437]
> This paper reports on a package called sciris that is dedicated to streamlining a certain type of scientific inquiry in Python. It strikes me as a valuable contribution and eventually worthy of publication in JOSS. Before I can confirm all of the items on the checklist, however, I think that the authors should address a number of points in their documentation and software paper.

> Documentation No statement of need, or statement of target audience. No list of dependencies (although pip install sciris handles them automatically for me). No example usage for the sciris package (and possibly confusing examples of a related scirisweb package. Extremely minimal documentation of core functionality, basically just formatted docstrings with no guidance about what is important or how it fits together. Lack of documentation on testing, although it seems like there are automated tests.

> Software Paper Statement of need does not identify who the target audience is, or its relation to other work. No State-of-the-field section to describe how this software compares to other commonly-used packages.

**Comment by cliffckerr** [comment]
cc https://github.com/openjournals/joss-reviews/issues/5076

**Comment by cliffckerr** [comment]
- I've tried to clarify the statement of need ("Sciris provides functions covering a wide range of common math, file I/O, and plotting operations. This means you can get more done with less code, and spend less time looking things up on StackOverflow.") and the target audience ("It was originally written to help epidemiologists and neuroscientists focus on doing science, rather than on writing coding, but Sciris is applicable across scientific domains."), but if either of these are unclear still, happy to edit.
- The dependencies are listed in `setup.py`, which I think is a sufficiently "discoverable" place for them, but again happy to amend (e.g. move to a separate `requirements.txt` file) if desired.
- It's a good point about minimal usage examples beyond docstrings. I had long thought that having tutorials was excessive since most of the functions are quite atomic and relatively simple, but I no longer think that :) Have made an issue here: https://github.com/sciris/sciris/issues/465. This will hopefully address the example usage and functionality points.
- For tests, I'm not sure what other documentation could be provided other than the tests folder, which includes a readme? I could mention this in the main readme ("The tests are in the tests folder"), but this seems redundant...
- I don't know of any *directly* comparable libraries to Sciris, but I do mention other libraries that have similar motivations (e.g., seaborn to make Matplotlib more accessible). I also added a reference to R's `tidyverse`, which I think is similar in intent (if very different in implementation) to Sciris.

**Comment by aflaxman** [comment]
This addresses almost all of my concerns.  The one point I would prefer a little more change on is the tests --- for users who are not experienced in python testing, I think it would be helpful to have a section in the docs that says (1) automatic tests exist, (2) this can confirm that things are working on your installation, and (3) here is how to run them and see that they have all passed.

**Comment by cliffckerr** [comment]
Thanks @aflaxman -- addressed here:
https://github.com/sciris/sciris/pull/468/commits/b61f123f9503291b78d097274ec9bcc578f5d96b
