### ISSUE TITLE
parallelizer='serial' or 'thread' doesn't have same deep-copying behaviour as running in parallel if arguments to different threads share objects

### ISSUE THREAD

**Issue by kelvinburke** [sciris/sciris#487]
Best explained with an example:
``sc.parallelize(func, iterkwargs={'dict':[common_dictionary, common_dictionary}, parallelizer='thread')``

Normally with ``parallelizer=None`` the two Processes will get two different deep-copied versions of the ``common_dictionary`` (through the pickling and unpickling process?) so any changes the the ``dict`` in the 1st process will not affect the ``dict`` in the 2nd process. 

However, just calling ``arglist = scu.dcp(arglist)`` doesn't make two different copies of the ``common_dictionary`` because ``copy.deepcopy()`` only creates a single new copy of each "sub-object" of an object. That is, ``arglist = scu.dcp(arglist)`` will create a new ``common_dictionary``, but it will be shared between the two Processes. 

For a test of dcp behaviour see [test_dcp.py.txt](https://github.com/sciris/sciris/files/11269278/test_dcp.py.txt). For a test of ``serial`` vs ``thread`` vs ``None`` as the parallelizer see [test_parallelize_dcp.py.txt](https://github.com/sciris/sciris/files/11269274/test_parallelize_dcp.py.txt)

I believe a fix is to replace
``argslist = scu.dcp(argslist)``
with
``argslist = [scu.dcp(args) for args in argslist]``

Then each ``args`` will be a new copy and will de-couple the shared objects and so ``parallelizer = 'serial', 'thread', None`` will all have the same behaviour

**Comment by kelvinburke** [comment]
Oh and this was in version ``2.1.0`` installed using ``pip install sciris``, but from the looks of the code, the ``rc3.0`` branch has the same behaviour.

**Comment by cliffckerr** [comment]
Thanks @kelvinburke ! Will take a look at this today.

**Comment by cliffckerr** [comment]
Well spotted @kelvinburke , took your solution and implemented it here: https://github.com/sciris/sciris/pull/481/commits/2b17fad3bc420888d41e9d2fae6036342c1b0846

Note that v3.0 defaults to _not_ copying, so
```
sc.parallelize(func, iterkwargs={'dict':[common_dictionary, common_dictionary}, parallelizer='thread')
```
would be
```
sc.parallelize(func, iterkwargs={'dict':[common_dictionary, common_dictionary}, parallelizer='thread-copy')
```
although if you actually want to pass the same argument to each function, as you probably know that would just be
```
sc.parallelize(func, ..., kwargs={'dict':common_dictionary}, parallelizer='thread-copy')
```
or for maximum brevity:
```
sc.parallelize(func, ..., dict=common_dictionary, parallelizer='thread-copy')
```

Thanks again!
