### ISSUE TITLE
odict slices don't respect step

### ISSUE THREAD

**Issue by kelvinburke** [sciris/sciris#545]
Hi @cliffckerr,
Slices can step by values other than 1 with the notation `list[0:5:2]`
odicts don't use the step value at all, and assume that it steps by 1 leading to some weird/incorrect behaviour.

I can elaborate more if you like, just putting this here so I don't forget

**Comment by cliffckerr** [comment]
Good catch, will fix!

**Comment by cliffckerr** [comment]
Done
