### ISSUE TITLE
Add option to descend into tuples in `iterobj`

### ISSUE THREAD

**Issue by kelvinburke** [sciris/sciris#552]
Hi @cliffckerr,
At the moment, none of `check_iter_type`, or `iteritems` etc work with tuples.

The expected behaviour would be that : 
 - if `inplace=True` that it creates a new tuple from the results of calling the function on the children and the new tuple replaces the old.
 - if `inplace=False`, then that new tuple goes into the output only as per usual.

If you want, tuple could be part of `_atomic_classes` so that tuples don't get descended into by default.

(btw thanks for your continued work on sciris the `iterobj` function is very useful! Although before I checked sciris I did pretty much reimplement it myself... haha)

**Comment by cliffckerr** [comment]
Thanks @kelvinburke ! Will include this in the next release (which will be done very soon).

**Comment by kelvinburke** [comment]
The only problem I can foresee is if there is a subclass of a tuple, then it should get replaced with a new instance of the subclass

**Comment by cliffckerr** [comment]
It's a little more complicated than that ... tuples are immutable, whereas `sc.iterobj()` assumes that there is a `set()`-like method for objects. That said, I have added this as an optional feature, and given a docstring example in the new `sc.IterObj()` class for it.

**Comment by cliffckerr** [comment]
Done

**Comment by kelvinburke** [comment]
Yes I thought that might be the case, thanks again!
