### ISSUE TITLE
`_task` copies `iterdict` values into `kwargs` which gets used in subsequent tasks

### ISSUE THREAD

**Issue by kelvinburke** [sciris/sciris#557]
Hi @cliffckerr 

I found a bug while:
 - Running `Parallel.run()` with `thread` or any other parallelizer that doesn't copy by default
 
Then the `Parallel.kwargs` is shared between all the `Taskargs.kwargs`. So `_task()` copies the values from `taskargs.iterdict` into the shared `Parallel.kwargs` : https://github.com/sciris/sciris/blob/1aa401005bf796452c62ba5cebc2e91eaeefb9af/sciris/sc_parallel.py#L814

This means that the Tasks after the first get the `iterdict` values in their `kwargs`.

Ideally we don't want to copy the `kwargs` if we haven't specified `thread-copy` so:
A fix would be to just call the function as 
```
result = func(*args, **kwargs, **taskargs.iterdict) # Call the function!
```
but then if `kwargs` and `taskargs.iterdict` share any keys then this will now throw an error when previous `kwargs` just got overriden by the `taskargs.iterdict` if they shared a key. What is the intended behaviour if they share keys?

I think it is fine that the `globaldict` gets put into the shared kwargs, because it is global anyway right?

Thanks!

**Comment by kelvinburke** [comment]
```
import sciris as sc

def func(**kwargs):
    return kwargs

if __name__ == '__main__':

    iterkwargs = [{'a':1}, {'b':2}]

    works = sc.parallelize(func, iterkwargs=iterkwargs)
    assert works == iterkwargs, f'{works} != {iterkwargs}'

    alsoworks = sc.parallelize(func, iterkwargs=iterkwargs, parallelizer='thread-copy')
    assert alsoworks == iterkwargs, f'{alsoworks} != {iterkwargs}'

    doesntwork = sc.parallelize(func, iterkwargs=iterkwargs, parallelizer='thread')
    assert doesntwork == iterkwargs, f'{doesntwork} != {iterkwargs}'

    doesntwork2 = sc.parallelize(func, iterkwargs=iterkwargs, parallelizer='serial')
    assert doesntwork2 == iterkwargs, f'{doesntwork2} != {iterkwargs}'
```

For easy replication or testing

**Comment by kelvinburke** [comment]
Found workaround so long as you aren't also using kwargs:

```
P = Parallel(func, iterarg=iterarg, iterkwargs=iterkwargs, args=args, kwargs=kwargs, ...)
P.kwargs = None  # initialising Parallel() gives P.kwargs = {}, even if you do Parallel(..., kwargs=None, ...)
# Run it
P.run()
```

**Comment by cliffckerr** [comment]
Closed by https://github.com/sciris/sciris/pull/558
