### ISSUE TITLE
Fix "class" in docs

### ISSUE THREAD

**Issue by cliffckerr** [sciris/sciris#589]
All the docs say "class" even when it's a function:
https://sciris.readthedocs.io/en/latest/api/_autosummary/sciris.sc_math.findinds.html
![image](https://github.com/sciris/sciris/assets/3239256/638ecb33-0600-426b-9334-3f80b6f84c50)

**Comment by JSchripsema-IDM** [comment]
I think this is an error in the function template (https://raw.githubusercontent.com/sciris/sciris/e127c3375e259fdd2a99e8e0cb7914e9c74890cd/docs/_templates/custom-function-template.rst). If you replace `autoclass` with `autofunction` it should work correctly.

**Comment by cliffckerr** [comment]
Fixed
